apiVersion: v1
kind: Service
metadata:
  labels:
    app: attestation-server
  name: registration-attestation-server
spec:
  ports:
  - name: registration-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: attestation-server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: attestation-server
  name: attestation-svc
spec:
  ports:
  - name: attestation-port
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: attestation-server
--- 
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: attestation-server
  name: attestation-svc
spec:
  host: ""
  port:
    targetPort: attestation-port
  to:
    kind: ""
    name: attestation-svc
    weight: null
