apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-repository
  namespace: attestation
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  volumeName: pv0024
