apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: confidential-deploy
  name: confidential-deploy
  namespace: untrusted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confidential-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: confidential-deploy
      annotations:
        run.oci.handler: "krun"
        krun/attestation: "http://172.30.115.41:8081/untrusted"
        krun/image: "image-registry.openshift-image-registry.svc:5000/untrusted/demo-encrypted-image@sha256:c20fac2b3812812b341bc9a585ee6521ac0707b9d820ce3721f2f33f7e96e5d6"
    spec:
      serviceAccountName: default
      runtimeClassName: crun-krun
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: virtee
                operator: In
                values:
                - "sev"
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/untrusted/demo-encrypted-image@sha256:a0c9e1297fe54e3a5acb50611b7225d8b76e4bba64bdd373ffd1189196bac918
        command:
        - "/entrypoint.sh"
        name: demo-encrypted-image
        stdin: true
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/kvm
          name: kvm
        - mountPath: /dev/sev
          name: sev
        - mountPath: /tmp
          name: tmp
        restartPolicy: Never
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          privileged: true
          unAsUser: 0
        resources:
          limits:
            memory: 3G
          requests:
            memory: 3G
      volumes:
      - name: kvm
        hostPath:
          path: /dev/kvm
      - name: sev
        hostPath:
          path: /dev/sev
      - hostPath:
          path: /tmp
        name: tmp
