apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: confidential-deploy
  name: confidential-deploy
  namespace: untrusted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confidential-deploy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: confidential-deploy
      annotations:
        run.oci.handler: "krun"
        krun/attestation: "http://172.30.115.41:8081/untrusted"
        krun/image: "image-registry.openshift-image-registry.svc:5000/untrusted/nginx-encrypted-image@sha256:6062cb500f074aff2e3d1f5380db90092262743f74fb5f6c063098d7cab4221c"
    spec:
      serviceAccountName: default
      runtimeClassName: crun-krun
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: virtee
                operator: In
                values:
                - "sev"
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/untrusted/nginx-encrypted-image
        command:
        - "/entrypoint.sh"
        name: demo-encrypted-image
        stdin: true
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/kvm
          name: kvm
        - mountPath: /dev/sev
          name: sev
        - mountPath: /tmp
          name: tmp
        restartPolicy: Never
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          privileged: true
          unAsUser: 0
        resources:
          limits:
            memory: 3G
          requests:
            memory: 3G
      volumes:
      - name: kvm
        hostPath:
          path: /dev/kvm
      - name: sev
        hostPath:
          path: /dev/sev
      - hostPath:
          path: /tmp
        name: tmp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: confidential-deploy
  name: confidential-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: confidential-deploy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: confidential-deploy
  name: confidential-deploy
spec:
  port:
    targetPort: 80
  to:
    kind: ""
    name: confidential-deploy
    weight: null
