apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: confidential-deploy
  name: confidential-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confidential-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: confidential-deploy
      annotations:
        run.oci.handler: "krun"
        krun/attestation: "http://172.30.115.41:8081/untrusted"
        krun/image: "image-registry.openshift-image-registry.svc:5000/untrusted/demo-encrypted-image:latest@sha256:a247307b785e50af863f672653794c541cd4bf7141e88f7ad1c3cbf5af666c47"
    spec:
      serviceAccountName: default
      runtimeClassName: crun-krun
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: virtee
                operator: In
                values:
                - "sev"
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/untrusted/demo-encrypted-image
        command:
        - "/entrypoint.sh"
        name: demo-encrypted-image
        stdin: true
        tty: true
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/kvm
          name: kvm
        - mountPath: /dev/sev
          name: sev
        - mountPath: /tmp
          name: tmp
        restartPolicy: Never
        securityContext:
          privileged: true
          unAsUser: 0
        resources:
          limits:
            memory: 3G
          requests:
            memory: 3G
      volumes:
      - name: kvm
        hostPath:
          path: /dev/kvm
      - name: sev
        hostPath:
          path: /dev/sev
      - hostPath:
          path: /tmp
        name: tmp
