apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tkn
spec:
  capacity:
    storage: 6Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /home/nfs-tkn
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tkn-images
  namespace: tekton-build
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: pv-tkn
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
